### ISSUE TITLE
[PE-D][Tester F] User Guide is long-winded

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-2/tp#190]
I like how comprehensive the User Guide is, however there is a lot of information at the start and can be quite a bit to read. 

For instance, I'm not sure if the "What's new" section, or the "How to use this Guide" section is needed. It also takes quite a while to get to the "Features" section, perhaps the information shared beforehand can be shortened.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wallywallywally/ped#1

**Comment by nkotaa** [comment]
The current state of the user guide is idiot-proofed to be readable to even non-technically inclined individuals. That is very much not the average PE dry-run tester, which explains your impatience.
