### ISSUE TITLE
[PE-D][Tester C] 2 Exact same add commands of the exact same item will cause 2 items to be listed in list

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-2/tp#211]
-------------------------------------------------------------
binbash> add -re -n "Special Paper" -d "For printing" -q 100 -s 2 -c 1 -t 20
-------------------------------------------------------------
Noted! I have added the following item into your inventory:

[R] "Special Paper"
	description: "For printing"
	quantity: 100
	cost price: $1.00
	sale price: $2.00
	threshold: 20
-------------------------------------------------------------
binbash> add -re -n "Special Paper" -d "For printing" -q 100 -s 2 -c 1 -t 20
-------------------------------------------------------------
Noted! I have added the following item into your inventory:

[R] "Special Paper"
	description: "For printing"
	quantity: 100
	cost price: $1.00
	sale price: $2.00
	threshold: 20
-------------------------------------------------------------

![Screenshot 2024-04-05 at 17.19.24.jpg](https://raw.githubusercontent.com/iscyng/ped/main/files/cc8da24f-413c-4602-8f05-7a98631b4a8d.jpg)

18. [R] "Special Paper"
	description: "For printing"
	quantity: 100
	cost price: $1.00
	sale price: $2.00
	threshold: 20

19. [R] "Special Paper"
	description: "For printing"
	quantity: 100
	cost price: $1.00
	sale price: $2.00
	threshold: 20

Maybe can check if they are the exact same items with the same flags and make it as if its restocking

![Screenshot 2024-04-05 at 17.16.44.jpg](https://raw.githubusercontent.com/iscyng/ped/main/files/093be115-bedf-48d0-8203-5d374288f8c0.jpg)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: iscyng/ped#9

**Comment by nkotaa** [comment]
Given that an item name is used to uniquely identify an item, an error message should rightly be thrown when an item with a duplicate name is added.
