### ISSUE TITLE
[PE-D][Tester E] Searching function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113T-T09-2/tp#217]
When i search for an item in my list that is not there, it returns an empty line. Can consider to display a message that no items was found to show that there was a response
![Screenshot 2024-04-05 at 5.24.42 PM.png](https://raw.githubusercontent.com/tannerlie/ped/main/files/54638966-75a4-4697-9ebb-63337df8c850.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: tannerlie/ped#1

**Comment by nkotaa** [comment]
Considered under enhancements.
