### ISSUE TITLE
minor code quality issues

### ISSUE THREAD

**Issue by okkhoy** [AY2324S2-CS2113T-T09-2/tp#274]
@PureUsagi
- you can consider using setup and teardown parts of the test if the prereqs to run the tests are similar

@imanamirshah
- `src/main/java/seedu/binbash/inventory/ItemList.java` in this file, some of the lines may be considered too long

**Comment by PureUsagi** [comment]
I seeee, thanks for the feedback prof!

**Comment by imanamirshah** [comment]
Thanks for the feedback prof! Will take a look at it and make the edits.

**Comment by okkhoy** [comment]
> Do you mean that the line is close to exceeding the 120 character limit

Yes
