### ISSUE TITLE
Implement profit margin calculation functionality

### ISSUE THREAD

**Issue by YHWong20** [AY2324S2-CS2113T-T09-2/tp#94]

**Comment by imanamirshah** [comment]
A simple profit analysis will be implemented for v2.0. 

Class-level attributes of `totalRevenue` and `totalCost` will be added to `ItemList` class. Whenever an item is restocked, the total cost price will be added to the `totalCost`. Whenever an item is sold, its total sale price will be added to `totalRevenue`.

Lets find a way to display `totalProfit`. It can either be displayed every time the application is started, or it can be implemented as a separate command to show all the relevant information such ash `totalRevenue`, `totalCost` and `totalProfit`.
